### ISSUE TITLE
Undeclared Identifier 'alphasort'

### ISSUE THREAD

**Issue by LittleSilver33** [etbala/boostport#4]
When trying to build boostport we get the following error:

fileunix.cpp:133:56: error: use of undeclared identifier 'alphasort'
    if ( -1 == ( n = scandir( dirstr, &namelist, NULL, alphasort ) ) )

It appears that alphasort is also a built in Unix command (similar to the other issue) and I am unsure as to why it isn't building on z/OS.

**Comment by EdenBendheim** [comment]
Issue resolved by adding an alpha sort function
